#pragma once

#define STRINGIFY_(v) #v
#define STRINGIFY(v) STRINGIFY_(v)

#define CXADC_CAPTURE_SERVER_VERSION STRINGIFY(CXADC_CAPTURE_SERVER_MAJOR) "." STRINGIFY(CXADC_CAPTURE_SERVER_MINOR) "." STRINGIFY(CXADC_CAPTURE_SERVER_PATCH)
